config/routes.rb
Projectjump::Application.routes.draw do
  devise_for :users

  get "welcome/index"

  resources :projects do 
    resources :updates
  end

  root :to => 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :active, :name, :repo_url, :task_tracker_url, :owner_id, :description

  has_many :updates,:dependent => :destroy
end

app/models/update.rb
class Update < ActiveRecord::Base
  attr_accessible :post, :title

  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,
         :token_authenticatable, :confirmable, :lockable, :timeoutable
         

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def user_auth
    unless user_signed_in?
        redirect_to "/users/sign_in"
    end
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :user_auth
  skip_before_filter :user_auth, :only => [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project].merge(:owner_id => current_user.id))

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController

  before_filter :load_parent

  # GET /updates
  # GET /updates.json
  def index
    @updates = @project.updates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @updates }
    end
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @update = Update.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/new
  # GET /updates/new.json
  def new
    @update = Update.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/1/edit
  def edit
    @update = Update.find(params[:id])
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(params[:update])

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render json: @update, status: :created, location: @update }
      else
        format.html { render action: "new" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /updates/1
  # PUT /updates/1.json
  def update
    @update = Update.find(params[:id])

    respond_to do |format|
      if @update.update_attributes(params[:update])
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    respond_to do |format|
      format.html { redirect_to updates_url }
      format.json { head :no_content }
    end
  end

  private
    def load_parent
      @project = Project.find(params[:project_id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Projectjump" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Projectjump</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "All Projects", "/projects"  %></li>
              <li><%= link_to "Start a Project", "/projects/new"  %></li>
              <li>
              </li>
              <!-- <li><%= link_to "", "/path3"  %></li> -->
            </ul>
            <div id="user_nav">
              <% if user_signed_in? %>
                Signed in as <%= current_user.email %> Not you?
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
              <% end %>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <!--<div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/allprojects"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :task_tracker_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :task_tracker_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :repo_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :repo_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :active, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :owner_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :owner_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="span12">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  </div>

    <% @projects.each do |project| %>
      <div class="project">
        <h3><%= link_to project.name, project %></h3>
        <div class="statusinfo">
          <span class="info"><span class="miniheader">Status:</span> <%= project.active ? "Active" : "Inactive"%></span>
          <span class="info"><span class="miniheader">Project Repository:</span> <%= project.repo_url %></span>
          <span class="info"><span class="miniheader">Task Tracker URL:</span>  <%= project.task_tracker_url %></span>
        </div>
        <div class="description">
          <div class="miniheader">Description:</div>
          <%= project.description %>
        </div>
      </div> 
      <hr/>
     <!-- <tr>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>-->
    <% end %>
</div>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="span12">
  <h1><%=t '.title', :default => @project.name %></h1>


  <!--<dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
    <dd><%= @project.active %></dd>
    <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
    <dd><%= @project.description %></dd>
  </dl>-->

  <ul class="nav nav-tabs">
    <li class="active" id="tab-overview">
      <a href="#" onclick="swap('overview')">Overview</a>
    </li>
    <li id="tab-contactinfo">
      <a href="#" onclick="swap('contactinfo')">Contact Information</a>
    </li>
    <li id="tab-blog">
      <a href="#" onclick="swap('blog')">Blog</a>
    </li>
  </ul>

  <div class="information" id="overview">
    <%= @project.description %>
  </div>
  <div class="information" id="contactinfo">
    <dl class="dl-horizontal">
      <dt><%= model_class.human_attribute_name(:task_tracker_url) %></dt>
      <dd><%= @project.task_tracker_url %></dd>
      <dt><%= model_class.human_attribute_name(:repo_url) %></dt>
      <dd><%= @project.repo_url %></dd>
      <dt><%= model_class.human_attribute_name(:owner_id) %></dt>
      <dd><%= User.find(@project.owner_id).email %></dd>
    </dl>
  </div>
  <div class="information" id="blog">
    <% @project.updates.each do |update| %>
      <b><%= update.title %></b><br/>
      <%= update.post %>
      <hr/>
    <% end %>
  </div>

  <!--
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                projects_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_project_path(@project), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                project_path(@project),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>
-->
</div>

app/views/updates/_form.html.erb
<%= form_for @update, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :post, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :post, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :project_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :project_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                updates_path, :class => 'btn' %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<%- model_class = Update -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/updates/index.html.erb
<%- model_class = Update -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:post) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= update.id %></td>
        <td><%= update.title %></td>
        <td><%= update.post %></td>
        <td><%= update.project_id %></td>
        <td><%=l update.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_project_update_path(update.project_id, update.id)%>
          <!--<%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_update_path(update), :class => 'btn btn-mini' %> -->
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      update_path(update),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_update_path(params[:project_id]),
            :class => 'btn btn-primary' %>

app/views/updates/new.html.erb
<%- model_class = Update -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/updates/show.html.erb
<%- model_class = Update -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @update.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:post) %>:</strong></dt>
  <dd><%= @update.post %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @update.project_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              updates_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_update_path(@update), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              update_path(@update),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>